RK_device_platform: RK1808
model_framework: onnx
model_file_path: ./resnet50v2.onnx
quantize: True
pre_compile: off
dataset: ./dataset.txt

graph:
  in_0:
    shape: 1,3,224,224
    mean_values: 123.675,116.28,103.53
    std_values: 58.395
    img_type: BGR

configs:
  quantized_dtype: asymmetric_quantized-u8
  quantized_algorithm: normal
  optimization_level: 3
  do_sparse_network: True
